server:
  port: 8086
spring:
  datasource:
    name: mysql_db
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/yueqian-fast?useSSL=FALSE&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 2
      maxActive: 50
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 900000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  profiles:
    active: dev
  web:
    resources:
      add-mappings: true

##mybaties 配置
mybatis:
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  mapperLocations: classpath*:mybatis/**/*Mapper.xml

#配置mybatisplus
mybatis-plus:
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

##分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
